@echo off
echo Setting up Risk System...

echo Creating venv for Agent 1...
python -m venv backend\agent1_risk\venv
echo Installing dependencies for Agent 1...
backend\agent1_risk\venv\Scripts\pip install -r backend\agent1_risk\requirements.txt

echo Creating venv for Agent 2...
python -m venv backend\agent2_traffic\venv
echo Installing dependencies for Agent 2...
backend\agent2_traffic\venv\Scripts\pip install -r backend\agent2_traffic\requirements.txt

echo Creating venv for Agent 3...
python -m venv backend\agent3_shadow\venv
echo Installing dependencies for Agent 3...
backend\agent3_shadow\venv\Scripts\pip install -r backend\agent3_shadow\requirements.txt

echo Creating venv for Agent 4...
python -m venv backend\agent4_learning\venv
echo Installing dependencies for Agent 4...
backend\agent4_learning\venv\Scripts\pip install -r backend\agent4_learning\requirements.txt

echo Setup Complete!
pause
